spring.application.name=EXP_10_Reconciliation

spring.datasource.url=jdbc:h2:file:./data/reconciliationdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8082

reconciliation.fixed-delay=10000
reconciliation.stale-after-seconds=30